language: cpp
sudo: required
compiler: gcc
env: QT_BASE="512"
cache: bundler
group: deprecated-2017Q4
before_install:
    - sudo add-apt-repository ppa:opt-qt-5.12.3-xenial;
    - sudo apt-get update -qq;
install:
    - sudo apt-get install -qq qt512-meta-minimal; source /opt/qt512/bin/qt512-env.sh;

script:
    - qmake
    - make
notifications:
    email: false
