version: '1.0.{build}'

branches:
  except:
    - project/travis

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      releaseName: DemoCI_win64

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" x64
  - set QTDIR=C:\Qt\5.12.5\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;
  - qmake
  - nmake & exit 0
